# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
defaults:
  run:
    working-directory: ./letsdecide
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        node-version: ['12']

    steps:
    - uses: actions/checkout@v2
    - uses: codecov/codecov-action@v1
    - name: Set up Node ${{matrix.node-version}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node-version}}


    - name: Install Dependencies
      run: |
        npm install
    - name: Test + Coverage - Jest
      run: |
        npm install
        npm test -- --watchAll=false --coverage
        
    - name: StandardJS lint checks
      uses: goto-bus-stop/standard-action@v1
      with:
        files: src/*.js
        annotate: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Codecov
      uses: codecov/codecov-action@v1.0.13
      with:
        # User defined upload name. Visible in Codecov UI
        name: LetsDecideCov
        # Repository upload token - get it from codecov.io. Required only for private repositories
        token: ${{ secrets.CODECOV_TOKEN }}
    

